config/routes.rb
Rails.application.routes.draw do

  root 'books#index'

  get 'login' => 'session#new', as: :login
  post 'login' => 'session#create'
  get 'logout' => 'session#delete', as: :logout

  get '/signup' => 'signup#new', as: :signup
  post '/signup' => 'signup#create', as: :users

  get 'authors' => 'authors#index', as: :authors
  get 'authors/new' => 'authors#new', as: :new_author
  post 'authors' => 'authors#create'
  get 'authors/:id' => 'authors#show', as: :author
  get 'authors/:id/edit' => 'authors#edit', as: :edit_author
  patch 'authors/:id' => 'authors#update'
  delete 'authors/:id' => 'authors#delete'

  get 'books' => 'books#index', as: :books
  get 'books/new' => 'books#new', as: :new_book
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: :book
  get 'books/:id/edit' => 'books#edit', as: :edit_book
  patch 'books/:id' => 'books#update'
  delete 'books/:id' => 'books#delete'

  get 'license' => 'public#license', as: :license

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  attachment :photo_id
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, :last_name, :email, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  before_action do
    @current_user = User.find_by id: session[:user_id]
    redirect_to login_path, alert: "Please login to continue." if @current_user.blank?
  end

  def index
    @authors = Author.all
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new
    @author.first_name = params[:author][:first_name]
    @author.last_name = params[:author][:last_name]
    @author.bio = params[:author][:bio]
    @author.save ? (redirect_to authors_path, notice: "New Author Created!") : (render :new)
  end

  def show
    @author = Author.find_by id: params[:id]
  end

  def edit
    @author = Author.find_by id: params[:id]
  end

  def update
    @author = Author.find_by id: params[:id]
    @author.first_name = params[:author][:first_name]
    @author.last_name = params[:author][:last_name]
    @author.bio = params[:author][:bio]
    @author.save ? (redirect_to author_path, notice: "Author Updated!") : (render :edit)
  end

  def delete
    @author = Author.find_by id: params[:id]
    @author.destroy ? (redirect_to authors_path, alert: "Author Deleted!") : (render :edit)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action do
    @current_user = User.find_by id: session[:user_id]
    redirect_to login_path, notice: "Please login to continue." if @current_user.blank?
  end

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new
    @book.title = params[:book][:title]
    @book.photo_url = params[:book][:title]
    @book.price = params[:book][:price]
    @book.author_id = params[:book][:author_id]
    @book.save ? (redirect_to books_path, notice: "Book Created!") : (render :new)
  end

  def show
    @book = Book.find_by id: params[:id]
  end

  def edit
    @book = Book.find_by id: params[:id]
  end

  def update
    @book = Book.find_by id: params[:id]
    @book.title = params[:book][:title]
    @book.photo_url = params[:book][:photo_url]
    @book.price = params[:book][:price]
    @book.author_id = params[:book][:author_id]
    @book.save ? (redirect_to book_path, notice: "Book Updated!") : (render :edit)
  end

  def delete
    @book = Book.find_by id: params[:id]
    @book.destroy ? (redirect_to books_path, alert: "Book Deleted!") : (render :edit)
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def license
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    email = params[:email]
    password = params[:password]
    @user = User.find_by email: email
    if @user.password == password
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Welcome #{@user.first_name}!"
    else
      render :new
    end
  end

  def delete
    session[:user_id] = nil
    redirect_to login_path, alert: "You have been logged out."
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.first_name = params[:user][:first_name]
    @user.last_name = params[:user][:last_name]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>
   <div class="mdl-textfield mdl-js-textfield">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "mdl-textfield__input" %>
   </div>
   <div class="mdl-textfield mdl-js-textfield">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "mdl-textfield__input" %>
   </div>
   <br>
   <div class="mdl-textfield mdl-js-textfield">
    <%= f.label :bio %>
    <%= f.text_field :bio, class: "mdl-textfield__input" %>
   </div>
   <br>
  <div>
      <%= f.submit class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
    </div>
<% end %>

app/views/authors/edit.html.erb
<h4>Edit <%= @author.first_name %> <%= @author.last_name %></h4>
<%= render partial: 'form' %>
<br>
<%= link_to "Delete Author", author_path(id: @author.id), method: :delete, :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored", data: {confirm: "Are you sure you want to remove this author?"} %>
<%= link_to "Return to Authors", authors_path, :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored" %>

app/views/authors/index.html.erb
<h4>Authors</h4>
<%= render :partial => 'layouts/flash' %>
<%= link_to "New Author", new_author_path, :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored" %>
<p>
<div>
  <% @authors.each do |author| %>
      <div class="card-square mdl-card mdl-shadow--2dp">
        <div class="mdl-card__title mdl-card--expand" style="background: url('')">
          <h2 class="mdl-card__title-text"><%= author.first_name %> <% author.last_name %></h2>
        </div>
        <div class="mdl-card__supporting-text">
          <%= author.bio %>
        </div>
        <div class="mdl-card__actions mdl-card--border">
          <%= link_to "More Details", author_path(id: author.id),
          class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %>
        </div>
      </div>
    <% end %>
</div>

app/views/authors/new.html.erb
<h4>New Author</h4>
<%= render partial: 'form' %>
<br>
<%= link_to "Return to Authors", authors_path, :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored" %>

app/views/authors/show.html.erb
<h4><%= @author.first_name %> <%= @author.last_name %></h4>

<%= @author.bio %>
<br>
<%= link_to "Edit Author", edit_author_path, :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored" %>
<%= link_to "Return to Authors", authors_path, :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored" %>

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
   <div class="mdl-textfield mdl-js-textfield">
    <%= f.label :title %>
    <%= f.text_field :title, class: "mdl-textfield__input" %>
   </div>
   <br>

   <div class="mdl-textfield mdl-js-textfield">
    <%= f.label :photo %>
    <%= f.attachment_field :photo_, class: "mdl-textfield__input" %>
   </div>
   <br>

   <div class="mdl-textfield mdl-js-textfield">
    <%= f.label :price %>
    <%= f.text_field :price, class: "mdl-textfield__input" %>
   </div>
   <br>

   <div class="mdl-textfield mdl-js-textfield">
    <%= f.label :author_id %>
    <%= f.text_field :author_id, class: "mdl-textfield__input" %>
   </div>
   <br>
  <div>
      <%= f.submit class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
    </div>
<% end %>

app/views/books/edit.html.erb
<h4>Edit <%= @book.title %></h4>
<%= render partial: 'form' %>
<br>
<%= link_to "Delete Book", book_path(id: @book.id), method: :delete, :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored", data: {confirm: "Are you sure you want to remove this book?"} %>
<%= link_to "Return to Books", books_path, :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored" %>

app/views/books/index.html.erb
<h4>Books</h4>
<%= render :partial => 'layouts/flash' %>
<%= link_to "New Book", new_book_path, :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored" %>
<p>
<div>
  <% @books.each do |book| %>
      <div class="card-square mdl-card mdl-shadow--2dp">
        <div class="mdl-card__title mdl-card--expand" style="background: url('<%= book.photo_url %>')">
          <h2 class="mdl-card__title-text"><%= book.title %></h2>
        </div>
        <div class="mdl-card__supporting-text">
          $<%= book.price %>0
        </div>
        <div class="mdl-card__actions mdl-card--border">
          <%= link_to "More Details", book_path(id: book.id),
          class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %>
        </div>
      </div>
    <% end %>
</div>

app/views/books/new.html.erb
<h4>New Book</h4>
<%= render partial: 'form' %>
<br>
<%= link_to "Return to Books", books_path, :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored" %>

app/views/books/show.html.erb
<h4><%= @book.title %></h4>

<h5>Author: <%= link_to "#{@book.author.first_name} #{@book.author.last_name}",
              author_path(id: @book.author.id) %><br></h5>
Price: $<%= @book.price %>0<br>
Photo URL: <%= @book.photo_url %>
<p>
<br>
<%= link_to "Edit Book", edit_book_path, :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored" %>
<%= link_to "Return to Books", books_path, :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored" %>

app/views/layouts/_flash.html.erb
<div class="row valign-wrapper">
  <div class="col s12 alert">
    <% if flash[:alert] %>
      <div class="alert"><%= flash[:alert] %></div>
    <% end %>
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Iron Library</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<header>
  <nav class="z-depth-0 transparent">
    <div class="nav-wrapper">
      <%= link_to "Iron Library", root_path, :class => "light-blue-text text-darken-2 brand-logo" %>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if @current_user %>
          <li><%= link_to "Books", books_path, :class => "light-blue-text text-darken-2" %></li>
          <li><%= link_to "Authors", authors_path,
            :class => "light-blue-text text-darken-2" %></li>
          <li><%= link_to "Logout", logout_path, :class => "light-blue-text text-darken-2" %></li>
        <% else %>
          <li><%= link_to "Login", login_path, :class => "light-blue-text text-darken-2" %></li>
          <li><%= link_to "Register", signup_path, :class => "light-blue-text text-darken-2" %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>
<main>
  <div class="container grey-text text-darken-2">
    <%= yield %>
  </div>
</main>
    <footer class="page-footer transparent">
      <div class="container">
        <div class="row valign-wrapper">
          <div class="col s12 grey-text center-align">
            <%= link_to "Iron Library", "http://ironlibrary.skylarcking.com",
            :class => "light-blue-text text-darken-2" %><br>
            © <%= Time.now.year %> <%= link_to "Skylar King", "http://www.skylarcking.com",
            :class => "light-blue-text text-darken-2" %><br>
            <%= link_to "View on Github", "https://github.com/skylarking/Iron-Library",
            :class => "light-blue-text text-darken-2" %><br>
            <%= link_to "Report an Issue", "https://github.com/skylarking/Iron-Library/issues/new",
            :class => "light-blue-text text-darken-2" %><br>
            <%= link_to "License", license_path, :class => "light-blue-text text-darken-2" %>
          </div>
        </div>
      </div>
    </footer>
  </div>
</body>
</html>

app/views/session/new.html.erb
<h5>Login</h5>
<%= render :partial => 'layouts/flash' %>
<%= form_tag do %>
  <div class="row">
    <div class="input-field col s12">
      <%= label_tag :email %><br>
      <%= text_field_tag :email %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= label_tag :password %><br>
      <%= password_field_tag :password %>
    </div>
  </div>
  <%= submit_tag "Login", class: "waves-effect waves-light btn light-blue darken-2 z-depth-0" %>
<% end %>

app/views/signup/new.html.erb
<h5>Register</h5>
<%= render :partial => 'layouts/flash' %>
<%= form_for @user do |f| %>
  <div class="row">
    <div class="input-field col s12">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name %>
   </div>
 </div>
 <div class="row">
   <div class="input-field col s12">
     <%= f.label :last_name %><br>
     <%= f.text_field :last_name %>
   </div>
 </div>
 <div class="row">
   <div class="input-field col s12">
     <%= f.label :email %><br>
     <%= f.text_field :email %>
   </div>
 </div>
 <div class="row">
   <div class="input-field col s12">
     <%= f.label :password %><br>
     <%= f.password_field :password %>
   </div>
 </div>
 <div>
   <%= f.submit class: "waves-effect waves-light btn light-blue darken-2 z-depth-0" %>
 </div>
<% end %>